local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/static/uploads"
publish_mode: editorial_workflow

collections:
  - name: "content"
    label: "Konten Situs"
    files:
      - name: "news"
        label: "Berita Terkini"
        file: "data/news.json"
        format: "json"
        fields:
          - label: "Daftar Berita"
            name: "entries"
            widget: "list"
            summary: "{{fields.tag}} - {{fields.title}}"
            fields:
              - { label: "Judul", name: "title", widget: "string" }
              - { label: "Kategori / Tag", name: "tag", widget: "string" }
              - {
                  label: "Gambar",
                  name: "image",
                  widget: "image",
                  allow_multiple: false,
                  choose_url: true,
                }
              - { label: "Ringkasan", name: "excerpt", widget: "text" }
              - {
                  label: "Tautan (Opsional)",
                  name: "link",
                  widget: "string",
                  required: false,
                }
      - name: "testimonials"
        label: "Apa Kata UMKM Binaan"
        file: "data/testimonials.json"
        format: "json"
        fields:
          - label: "Daftar Testimoni"
            name: "entries"
            widget: "list"
            fields:
              - { label: "Testimoni", name: "quote", widget: "text" }
              - { label: "Nama", name: "name", widget: "string" }
              - {
                  label: "Peran / Usaha",
                  name: "role",
                  widget: "string",
                  required: false,
                }

      - name: "partners"
        label: "Mitra & Kolaborator"
        file: "data/partners.json"
        format: "json"
        fields:
          - label: "Daftar Mitra"
            name: "entries"
            widget: "list"
            fields:
              - { label: "Nama Mitra", name: "name", widget: "string" }
              - {
                  label: "Tautan (Opsional)",
                  name: "url",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Logo",
                  name: "logo",
                  widget: "image",
                  choose_url: true,
                }
